#Database Configuration
#Thu Apr 30 12:03:43 PDT 2026
db.password=
db.url=jdbc\:mysql\://localhost\:3306/attendance_db?useSSL\=false&serverTimezone\=UTC&allowPublicKeyRetrieval\=true
db.username=root
